version: '2'
services:
  backend:
    image: gcr.io/fpt-fti/ikhien:0.0.5
    environment:
      - SL_MONGO_URL=mongodb://mongo:27017/ekyc?authSource=admin
    ports:
      - "3000:5000"
    depends_on:
      - mongo
    command: node server.js
    restart: always

  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - ./mongo_data:/data/db

